2021-08-06 09:58:27,261 ERROR: Exception on /follow/fhr [GET] [in C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\python\PyCharmWork\microblog\app\main\routes.py", line 108, in follow
    flash(_('You are following %{username}!', username=username))
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask_babel\__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask_babel\__init__.py", line 588, in gettext
    return s if not variables else s % variables
ValueError: unsupported format character '{' (0x7b) at index 19
2021-08-06 10:00:22,434 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:65]
2021-08-06 10:00:32,911 ERROR: Exception on /unfollow/fhr [GET] [in C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\python\PyCharmWork\microblog\app\main\routes.py", line 125, in unfollow
    flash(_('You are following %{username}!', username=username))
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask_babel\__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask_babel\__init__.py", line 588, in gettext
    return s if not variables else s % variables
ValueError: unsupported format character '{' (0x7b) at index 19
2021-08-06 10:00:54,871 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:65]
